apiVersion: v1
kind: Service
metadata:
  name: openresty
  labels:
    app: openresty
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 31704
      protocol: TCP
      name: openresty
  selector:
    app: openresty
